"""remove preconfigured tools

Revision ID: 3aac0925fbe0
Revises: 515b5e6425ae
Create Date: 2025-05-14 13:10:10.946040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3aac0925fbe0'
down_revision: Union[str, None] = '515b5e6425ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_preconfigured_mcp_tools_preconfigured_mcp_config_id', table_name='preconfigured_mcp_tools')
    op.drop_table('preconfigured_mcp_tools')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preconfigured_mcp_tools',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('inputSchema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('preconfigured_mcp_config_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['preconfigured_mcp_config_id'], ['preconfigured_mcp_configs.id'], name='preconfigured_mcp_tools_preconfigured_mcp_config_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='preconfigured_mcp_tools_pkey')
    )
    op.create_index('ix_preconfigured_mcp_tools_preconfigured_mcp_config_id', 'preconfigured_mcp_tools', ['preconfigured_mcp_config_id'], unique=False)
    # ### end Alembic commands ###
