"""add unique code

Revision ID: 515b5e6425ae
Revises: 336a3dbd5658
Create Date: 2025-05-14 11:42:12.802515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515b5e6425ae'
down_revision: Union[str, None] = '336a3dbd5658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_configs', sa.Column('code', sa.String(length=4), nullable=False))
    op.create_unique_constraint('uq_code', 'mcp_configs', ['code', 'user_id'])
    op.add_column('mcp_tools', sa.Column('code', sa.String(length=62), nullable=False))
    op.create_unique_constraint('uq_tool_code', 'mcp_tools', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tool_code', 'mcp_tools', type_='unique')
    op.drop_column('mcp_tools', 'code')
    op.drop_constraint('uq_code', 'mcp_configs', type_='unique')
    op.drop_column('mcp_configs', 'code')
    # ### end Alembic commands ###
