"""add config type

Revision ID: 9230c6e30018
Revises: 3aac0925fbe0
Create Date: 2025-05-16 14:03:23.728680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9230c6e30018'
down_revision: Union[str, None] = '3aac0925fbe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('StreamableHTTP', 'SSE', 'DockerRun', 'Npx', 'Uvx', name='mcpconfigtype').create(op.get_bind())
    op.add_column('mcp_configs', sa.Column('type', postgresql.ENUM('StreamableHTTP', 'SSE', 'DockerRun', 'Npx', 'Uvx', name='mcpconfigtype', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_configs', 'type')
    sa.Enum('StreamableHTTP', 'SSE', 'DockerRun', 'Npx', 'Uvx', name='mcpconfigtype').drop(op.get_bind())
    # ### end Alembic commands ###
