"""provider column not null

Revision ID: 8354746ad6c3
Revises: 9c367746cee5
Create Date: 2025-05-06 08:10:34.235982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8354746ad6c3'
down_revision: Union[str, None] = '9c367746cee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
