"""add config type

Revision ID: 980844ce2369
Revises: 3aac0925fbe0
Create Date: 2025-05-16 14:49:20.731299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '980844ce2369'
down_revision: Union[str, None] = '3aac0925fbe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_configs', sa.Column('type', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_configs', 'type')
    # ### end Alembic commands ###
