"""provider column, remove meta

Revision ID: 9c367746cee5
Revises: b4aeda6741d0
Create Date: 2025-05-06 07:58:35.244833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c367746cee5'
down_revision: Union[str, None] = 'b4aeda6741d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('provider', sa.String(), nullable=True))
    op.drop_column('messages', 'meta')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('messages', 'provider')
    # ### end Alembic commands ###
