"""tttt

Revision ID: d8e7295fbb85
Revises: ca20c37c3802
Create Date: 2025-05-01 13:53:55.896174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8e7295fbb85'
down_revision: Union[str, None] = 'ca20c37c3802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('pending', 'approved', 'rejected', name='toolusestate').create(op.get_bind())
    op.add_column('mcp_tool_uses', sa.Column('state', postgresql.ENUM('pending', 'approved', 'rejected', name='toolusestate', create_type=False), nullable=False))
    op.drop_column('mcp_tool_uses', 'approved')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_tool_uses', sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('mcp_tool_uses', 'state')
    sa.Enum('pending', 'approved', 'rejected', name='toolusestate').drop(op.get_bind())
    # ### end Alembic commands ###
