"""add constraints

Revision ID: b4aeda6741d0
Revises: 854ed9f00a7c
Create Date: 2025-05-05 18:21:27.280300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4aeda6741d0'
down_revision: Union[str, None] = '854ed9f00a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_provider', 'api_keys', ['user_id', 'provider'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_provider', 'api_keys', type_='unique')
    # ### end Alembic commands ###
