"""remove config col add preconfigured

Revision ID: 336a3dbd5658
Revises: 8354746ad6c3
Create Date: 2025-05-13 15:09:14.656389

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "336a3dbd5658"
down_revision: Union[str, None] = "8354746ad6c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "preconfigured_mcp_configs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_preconfigured_mcp_configs_user_id"),
        "preconfigured_mcp_configs",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "preconfigured_mcp_tools",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("inputSchema", sa.JSON(), nullable=False),
        sa.Column("preconfigured_mcp_config_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["preconfigured_mcp_config_id"],
            ["preconfigured_mcp_configs.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_preconfigured_mcp_tools_preconfigured_mcp_config_id"),
        "preconfigured_mcp_tools",
        ["preconfigured_mcp_config_id"],
        unique=False,
    )
    op.drop_column("mcp_configs", "configuration")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mcp_configs",
        sa.Column(
            "configuration",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(
        op.f("ix_preconfigured_mcp_tools_preconfigured_mcp_config_id"),
        table_name="preconfigured_mcp_tools",
    )
    op.drop_table("preconfigured_mcp_tools")
    op.drop_index(
        op.f("ix_preconfigured_mcp_configs_user_id"),
        table_name="preconfigured_mcp_configs",
    )
    op.drop_table("preconfigured_mcp_configs")
    # ### end Alembic commands ###
