"""Add mcp_tools table

Revision ID: 16e04bc3a890
Revises: 139981c02e52
Create Date: 2025-04-29 19:24:01.888948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e04bc3a890'
down_revision: Union[str, None] = '139981c02e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_tools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mcp_config_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('inputSchema', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['mcp_config_id'], ['mcp_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_tools_id'), 'mcp_tools', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mcp_tools_id'), table_name='mcp_tools')
    op.drop_table('mcp_tools')
    # ### end Alembic commands ###
